### ISSUE TITLE
Vectored interrupts and USB

### ISSUE THREAD

**Issue by esmil** [lundmar/riscv-gd32vf103-demo#1]
Hi Martin,

I came across this and though you might want to have a look at [gd32vf103inator](https://github.com/esmil/gd32vf103inator). The interrupt controller on the gd32vf103 has a [vectored mode](https://github.com/esmil/gd32vf103inator/blob/master/lib/eclic.c#L42) and some [special CSRs ](https://github.com/esmil/gd32vf103inator/blob/master/start.S#L192) to handle nested interrupts and tail-chaining.

In the same repo is also code to get USB up and running and a DFU bootloader that works with a non-patched dfu-utils.

/Emil

**Comment by lundmar** [comment]
Hi Emil,
Thanks for the information.
However, I think the current configuration is good enough for demonstration purposes. If you need vectored and nested interrupts etc. you are free to do the reconfiguration for your specific application need.
/Martin
